### ISSUE TITLE
使用DowngradeOK-0.0.3.plugin之后，无法显示/找不到betterNCM界面

### ISSUE THREAD

**Issue by Catfl** [BetterNCM/BetterNCM-Plugins#552]
我在使用了DowngradeOK-0.0.3.plugin插件之后，找不到betterNCM的设置界面

**Comment by Catfl** [comment]
![image](https://github.com/BetterNCM/BetterNCM-Plugins/assets/53962672/fc84b930-3370-462c-ae1c-3875df319c8f)

**Comment by MicroCBer** [comment]
降级后可能需要重新安装betterncm
