### ISSUE TITLE
InfLink插件 没有传输时间信息

### ISSUE THREAD

**Issue by Monodesu** [BetterNCM/BetterNCM-Plugins#638]
![image](https://github.com/user-attachments/assets/3aa42734-0e91-4bb1-81bc-a2de6797153d)
开始时间，当前时间，结束时间全部都是空

正常应该是这样：
![image](https://github.com/user-attachments/assets/640fb1de-431a-463f-98a7-01f2247a8d3a)

**Comment by std-microblock** [comment]
这个问题已经被pr修复了，不过我暂时还没有时间重新编译二进制以及发版，稍等一两个星期哈
